version: '3'

services:
  web:
    image: elhardoum/ticker-tracker:latest
    restart: always
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    env_file: .env
  
  mssql:
    image: elhardoum/ticker-tracker-db:latest
    volumes:
      - ./db:/usr/src/app
      - ./mssql:/var/opt/mssql/data
    working_dir: /usr/src/app
    env_file: .env
    ports:
      - 1433:1433
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
