version: '3'

services:
  web:
    image: elhardoum/ticker-tracker:latest
    restart: always
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    env_file: .env
