name: Docker CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: local unit tests
      env:
        ACCEPT_EULA: Y
        SA_PASSWORD: SuchPa$$word2204
      run: |
        test -f .env || touch .env
        docker-compose build -q
        docker-compose run --rm -e ENVIRONMENT=test web
