name: Docker Image CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: local unit tests
      run: docker run --rm -e ENVIRONMENT=test $(docker build -q .)
