name: Docker CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: local unit tests
      env:
        ACCEPT_EULA: Y
        SA_PASSWORD: SuchPa$$word2204
        ENVIRONMENT: test
      run: |
        env > .env
        docker-compose build --no-cache
        docker-compose run --rm

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        USER: ${{ secrets.DOCKER_USER }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $USER -p $PASSWORD
    - name: check dotnet file
      run: test -f .env || touch .env
    - name: Build the Docker image
      run: docker-compose build --no-cache
    - name: docker push
      run: docker-compose push

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/ticker-tracker
          git pull origin master
          docker rmi --force elhardoum/ticker-tracker:latest
          docker rmi --force elhardoum/ticker-tracker-db:latest
          docker-compose build --no-cache --pull
          docker-compose up -d --force-recreate
