name: Docker CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: local unit tests
      env:
        ACCEPT_EULA: Y
        SA_PASSWORD: SuchPa$$word2204
        ENVIRONMENT: test
      run: |
        env > .env
        docker-compose build -q --no-cache
        docker-compose run --rm
