name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        USER: ${{ secrets.DOCKER_USER }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $USER -p $PASSWORD
    - name: Build the Docker image
      run: docker build . -t elhardoum/ticker-tracker:latest
    - name: docker push
      run: docker push elhardoum/ticker-tracker:latest

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/ticker-tracker
          git pull origin master
          docker rmi --force elhardoum/ticker-tracker:latest
          docker-compose build --no-cache --pull
          docker-compose up -d --force-recreate
